### ISSUE TITLE
it might be a minor bug at the file model.py, on line 239

### ISSUE THREAD

**Issue by linhduongtuan** [vithursant/nanoGPT_mlx#1]
Dear Vithursan,

Thank you for releasing the PR. I love it and am trying to run your source code. However, it might be a minor bug at the file model.py, on line 239. It should be ```self.ln_f = nn.LayerNorm(config.n_embd, config.bias)``` instead ```self.ln_f = nn.LayerNorm(config.n_embd, bias=config.bias)```

Best regards,
Linh

**Comment by vithursant** [comment]
Hi @linhduongtuan , thanks for pointing this out. Sorry, the arguments are correct but I was using `nn.LayerNorm` instead of the local `LayerNorm` function here (https://github.com/vithursant/nanoGPT_mlx/blob/b8bffb023124956a169482687b9693003e9da3c8/model.py#L9). The local LayerNorm I added supports optional `bias` similar to nanoGPT. In the Apple MLX version of LayerNorm, it also doesn't have an optional bias if you see here (https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.LayerNorm.html?highlight=layernorm#mlx.nn.LayerNorm).

Commit b8bffb0 fixes this issue.

**Comment by linhduongtuan** [comment]
Hi @vithursant,
Thank you for your explanation.
Best,
Linh

**Comment by vithursant** [comment]
No problem @linhduongtuan, thanks!

Commit https://github.com/vithursant/nanoGPT_mlx/commit/b8bffb023124956a169482687b9693003e9da3c8 closes #1
